"""Keyword lists: topics, local relevance, life-stage hints and sensationalism markers.

Everything is written in lowercase without accents (matching text.normalize).
"""

TOPIC_KEYWORDS: dict[str, list[str]] = {
    "world": [
        "war", "guerra", "ceasefire", "alto el fuego", "summit", "cumbre", "onu", "united nations", "naciones unidas", "nato", "otan",
        "diplomat", "diplomacia", "sanctions", "sanciones", "invasion", "refugees", "refugiados",
        "foreign minister", "canciller", "ukraine", "ucrania", "russia", "rusia", "china", "gaza",
        "israel", "iran", "europe", "europa", "treaty", "tratado", "border", "frontera", "embassy", "embajada",
    ],
    "politics": [
        "election", "elections", "elecciones", "eleccion", "president", "presidente", "presidenta",
        "congress", "congreso", "senate", "senado", "parliament", "parlamento", "minister", "ministro",
        "ministra", "government", "gobierno", "opposition", "oposicion", "vote", "votacion", "law", "ley",
        "court", "corte", "supreme court", "tribunal", "legislators", "diputados", "senadores", "campaign",
        "campana", "decree", "decreto", "prime minister", "primer ministro", "cabinet", "gabinete",
    ],
    "economy": [
        "inflation", "inflacion", "gdp", "pbi", "pib", "recession", "recesion", "interest rate", "tasa",
        "tasas", "central bank", "banco central", "imf", "fmi", "dollar", "dolar", "peso", "exports",
        "exportaciones", "imports", "importaciones", "tariff", "tariffs", "aranceles", "arancel", "debt",
        "deuda", "unemployment", "desempleo", "desocupacion", "salaries", "salarios", "wages", "budget",
        "presupuesto", "taxes", "impuestos", "economy", "economia", "markets", "mercados", "reserves",
        "reservas", "jobs", "empleo", "pensions", "jubilaciones", "prices", "precios", "bonds", "bonos",
    ],
    "business": [
        "company", "empresa", "empresas", "merger", "fusion", "acquisition", "adquisicion", "shares",
        "acciones", "stock", "bolsa", "earnings", "ganancias", "ceo", "startup", "investment", "inversion",
        "bank", "banco", "oil", "petroleo", "industry", "industria", "retail",
    ],
    "science": [
        "scientists", "cientificos", "study", "estudio", "research", "investigacion", "nasa", "space",
        "espacio", "telescope", "telescopio", "species", "especie", "fossil", "fosil", "physics", "fisica",
        "biology", "biologia", "astronomers", "astronomos", "discovery", "descubrimiento", "mars", "marte",
        "moon", "luna", "genome", "genoma", "nobel",
    ],
    "technology": [
        "artificial intelligence", "inteligencia artificial", "ai", "ia", "chip", "chips", "semiconductor",
        "semiconductores", "software", "app", "apple", "google", "microsoft", "openai", "anthropic",
        "nvidia", "cyberattack", "ciberataque", "hackers", "smartphone", "internet",
        "robot", "robots", "tesla", "satellite", "satelite", "technology", "tecnologia", "quantum", "cuantica",
    ],
    "health": [
        "health", "salud", "hospital", "hospitales", "vaccine", "vacuna", "vacunas", "virus", "outbreak",
        "brote", "disease", "enfermedad", "cancer", "world health organization", "oms", "patients", "pacientes", "doctors",
        "medicos", "epidemic", "epidemia", "pandemic", "pandemia", "dengue", "drug", "medicamento",
        "medicamentos", "mental health", "salud mental", "obesity", "obesidad",
    ],
    "environment": [
        "climate", "clima", "climate change", "cambio climatico", "emissions", "emisiones", "wildfire",
        "incendio", "incendios", "drought", "sequia", "flood", "floods", "inundacion", "inundaciones",
        "hurricane", "huracan", "earthquake", "terremoto", "sismo", "deforestation", "deforestacion",
        "renewable", "renovables", "pollution", "contaminacion", "heatwave", "ola de calor",
    ],
    "education": [
        "school", "schools", "escuela", "escuelas", "university", "universidad", "universidades",
        "students", "estudiantes", "teachers", "docentes", "education", "educacion", "exam", "examen",
    ],
    "culture": [
        "film", "pelicula", "cine", "music", "musica", "museum", "museo", "book", "libro", "literature",
        "literatura", "festival", "art", "arte", "exhibition", "exposicion", "oscar", "grammy",
    ],
    "sports": [
        "football", "futbol", "soccer", "world cup", "mundial", "copa", "tennis", "tenis", "olympics",
        "olimpicos", "nba", "f1", "formula 1", "match", "goal", "gol", "messi", "seleccion",
        "champions", "libertadores", "rugby", "torneo", "tournament",
    ],
    "security": [
        "police", "policia", "crime", "crimen", "delito", "robbery", "robo", "murder", "asesinato",
        "homicidio", "drug trafficking", "narcotrafico", "arrested", "detenido", "detenidos", "attack",
        "ataque", "shooting", "tiroteo", "terrorism", "terrorismo",
    ],
    "latam": [
        "latin america", "america latina", "latinoamerica", "argentina", "brazil", "brasil", "chile",
        "uruguay", "paraguay", "bolivia", "peru", "colombia", "venezuela", "ecuador", "mexico", "mercosur",
        "cuba", "lula", "milei",
    ],
}

# Words that suggest a local story for each country (normalized).
COUNTRY_KEYWORDS: dict[str, list[str]] = {
    "AR": ["argentina", "argentino", "argentinos", "argentinas", "buenos aires", "caba", "conurbano",
           "casa rosada", "milei", "bcra", "indec", "anses", "afip", "arca", "cordoba", "rosario",
           "mendoza", "santa fe", "tucuman", "patagonia", "malvinas", "falklands"],
    "ES": ["espana", "spain", "spanish", "espanol", "espanoles", "madrid", "barcelona", "cataluna",
           "moncloa", "congreso de los diputados", "andalucia", "valencia", "pais vasco"],
    "MX": ["mexico", "mexican", "mexicano", "mexicanos", "cdmx", "sheinbaum", "morena", "jalisco",
           "monterrey", "guadalajara", "banxico"],
    "US": ["united states", "american", "americans", "estados unidos", "eeuu", "washington",
           "white house", "casa blanca", "congress", "federal reserve", "fed"],
    "CL": ["chile", "chileno", "chilenos", "santiago de chile", "la moneda", "valparaiso"],
    "UY": ["uruguay", "uruguayo", "uruguayos", "montevideo"],
    "CO": ["colombia", "colombiano", "colombianos", "bogota", "medellin", "cali"],
    "PE": ["peru", "peruano", "peruanos", "lima"],
    "GB": ["uk", "britain", "british", "england", "scotland", "wales", "london", "downing street",
           "reino unido", "londres"],
}

# Gentle hints about what tends to matter at each life stage. They only add a
# small boost and can be switched off with profile.use_age_hints: false.
AGE_HINTS: list[tuple[int, int, list[str]]] = [
    (0, 25, ["university", "universidad", "students", "estudiantes", "scholarship", "beca",
             "first job", "primer empleo", "rent", "alquiler", "alquileres"]),
    (25, 45, ["mortgage", "hipoteca", "credito hipotecario", "rent", "alquiler", "alquileres",
              "salaries", "salarios", "wages", "jobs", "empleo", "childcare", "schools", "escuelas"]),
    (45, 65, ["pensions", "jubilaciones", "retirement", "jubilacion", "salaries", "salarios",
              "taxes", "impuestos", "health", "salud", "savings", "ahorro"]),
    (65, 200, ["pensions", "jubilaciones", "jubilados", "retirement", "pami", "health", "salud",
               "medicamentos", "medicines", "hospital"]),
]

# Opinion / commentary is excluded: we want reporting, not takes.
OPINION_URL_PARTS = ["/opinion", "/opinión", "/editorial", "/columnistas", "/columnas/", "/blogs/",
                     "/tribuna/", "/cartas-", "/analisis-opinion", "/comment/", "/commentisfree/"]
OPINION_TITLE_PREFIXES = ["opinion", "opinion:", "editorial", "column", "columna", "tribuna",
                          "carta de lectores", "commentary", "op-ed"]

# Markers of hype / loaded language. Each hit lowers a story's score and makes
# that outlet's headline less likely to be the one shown.
SENSATIONAL = [
    "shocking", "shock", "slams", "blasts", "destroys", "obliterates", "rips", "outrage", "furious",
    "you won't believe", "jaw-dropping", "bombshell", "viral", "goes viral", "meltdown", "epic",
    "insane", "chaos", "explosive", "brutal", "humiliates", "fury", "stunning", "must see",
    "impactante", "escandalo", "escandaloso", "polemica", "polemico", "furor", "explota", "estalla",
    "insolito", "increible", "tremendo", "tremenda", "fuerte cruce", "durisimo", "durisima",
    "lapidario", "lapidaria", "humillo", "humillante", "liquido", "destrozo", "fulmino", "arraso",
    "se viralizo", "viralizo", "mira", "video:", "el video", "la foto", "las fotos", "atencion",
    "ultimo momento", "urgente", "bomba", "picante", "escandalosa",
]

UI = {
    "en": {
        "top": "Most important now",
        "local": "Your country",
        "updated": "Updated",
        "articles": "{n} articles read",
        "refresh": "Refresh",
        "settings": "Settings",
        "topics_title": "Your topics",
        "topics_hint": "Pick the tabs you want and their order. The order also sets what comes first in “Most important now”.",
        "add_topic_title": "Add your own topic",
        "topic_name": "Name (e.g. Energy)",
        "topic_keywords": "Keywords, separated by commas (e.g. oil, gas, lithium, petróleo)",
        "add": "Add",
        "remove": "Remove",
        "move_up": "Move up",
        "move_down": "Move down",
        "show_local": "Show the “Your country” tab",
        "save": "Save",
        "cancel": "Cancel",
        "reset": "Reset to defaults",
        "empty_tab": "No stories on this topic right now.",
        "read_full": "Read the full story",
        "covered_by": "Covered by",
        "settings_note": "These settings are saved on this device. The morning notification uses the topics in config.yaml.",
        "push_title": "Your daily news is ready",
        "bell_on": "Daily reminder on",
        "bell_off": "Turn on daily reminder",
        "push_unsupported": "This browser can't receive notifications.",
        "push_ios": "On iPhone, add this site to your Home Screen first (Share → Add to Home Screen), then open it from there and tap the bell again.",
        "push_denied": "Notifications are blocked. Allow them for this app in your phone's settings, then try again.",
        "push_failed": "Couldn't turn on notifications: {err}",
        "push_step1": "Last step: copy this code and save it in GitHub as the secret PUSH_SUBSCRIPTIONS. If you already have codes from other devices, put each on its own line.",
        "push_copy": "Copy code",
        "push_copied": "Copied ✓",
        "push_open_github": "Open GitHub secrets",
        "push_done": "Done",
        "push_off_hint": "You'll get a reminder every morning with the top headlines.",
        "sources_one": "1 outlet",
        "sources_many": "{n} outlets",
        "single_source": "single source",
        "why": "Why you see this",
        "covered": "covered by {n} independent outlets",
        "matches": "matches",
        "local_match": "relevant to {country}",
        "read_at": "Read at",
        "empty": "No stories right now. Check back after the next update.",
        "greeting": "Good morning! Your news for {date}",
        "more": "More on the site",
        "about": "Stories are ranked by how many independent outlets report them, how recent they are and how well they match your profile. Opinion pieces are excluded and hyped headlines are down-ranked.",
        "topics": {
            "world": "World", "politics": "Politics", "economy": "Economy", "business": "Business",
            "science": "Science", "technology": "Technology", "health": "Health",
            "environment": "Environment", "education": "Education", "culture": "Culture",
            "sports": "Sports", "security": "Security", "latam": "Latin America",
        },
    },
    "es": {
        "top": "Lo más importante",
        "local": "Tu país",
        "updated": "Actualizado",
        "articles": "{n} artículos leídos",
        "refresh": "Actualizar",
        "settings": "Ajustes",
        "topics_title": "Tus temas",
        "topics_hint": "Elegí las pestañas que querés y su orden. El orden también define qué aparece primero en “Lo más importante”.",
        "add_topic_title": "Agregar un tema propio",
        "topic_name": "Nombre (ej. Energía)",
        "topic_keywords": "Palabras clave separadas por comas (ej. petróleo, gas, litio, Vaca Muerta)",
        "add": "Agregar",
        "remove": "Quitar",
        "move_up": "Subir",
        "move_down": "Bajar",
        "show_local": "Mostrar la pestaña “Tu país”",
        "save": "Guardar",
        "cancel": "Cancelar",
        "reset": "Volver a los valores iniciales",
        "empty_tab": "No hay noticias de este tema por ahora.",
        "read_full": "Leer la nota completa",
        "covered_by": "Cubierto por",
        "settings_note": "Estos ajustes se guardan en este dispositivo. La notificación de la mañana usa los temas de config.yaml.",
        "push_title": "Tus noticias de hoy están listas",
        "bell_on": "Recordatorio diario activado",
        "bell_off": "Activar recordatorio diario",
        "push_unsupported": "Este navegador no puede recibir notificaciones.",
        "push_ios": "En iPhone, primero agregá este sitio a tu pantalla de inicio (Compartir → Agregar a inicio), abrilo desde ahí y tocá la campanita de nuevo.",
        "push_denied": "Las notificaciones están bloqueadas. Permitilas para esta app en los ajustes del teléfono y volvé a intentar.",
        "push_failed": "No se pudieron activar las notificaciones: {err}",
        "push_step1": "Último paso: copiá este código y guardalo en GitHub como el secreto PUSH_SUBSCRIPTIONS. Si ya tenés códigos de otros dispositivos, poné cada uno en su propia línea.",
        "push_copy": "Copiar código",
        "push_copied": "Copiado ✓",
        "push_open_github": "Abrir secretos de GitHub",
        "push_done": "Listo",
        "push_off_hint": "Vas a recibir un recordatorio cada mañana con los titulares principales.",
        "sources_one": "1 medio",
        "sources_many": "{n} medios",
        "single_source": "fuente única",
        "why": "Por qué lo ves",
        "covered": "cubierto por {n} medios independientes",
        "matches": "coincide con",
        "local_match": "relevante para {country}",
        "read_at": "Leer en",
        "empty": "No hay noticias por ahora. Volvé a mirar después de la próxima actualización.",
        "greeting": "¡Buen día! Tus noticias del {date}",
        "more": "Más en el sitio",
        "about": "Las noticias se ordenan según cuántos medios independientes las cubren, qué tan recientes son y cuánto coinciden con tu perfil. Se excluyen columnas de opinión y se penalizan los titulares sensacionalistas.",
        "topics": {
            "world": "Mundo", "politics": "Política", "economy": "Economía", "business": "Negocios",
            "science": "Ciencia", "technology": "Tecnología", "health": "Salud",
            "environment": "Ambiente", "education": "Educación", "culture": "Cultura",
            "sports": "Deportes", "security": "Seguridad", "latam": "América Latina",
        },
    },
}

LOCK_UI = {
    "en": {"placeholder": "Password", "remember": "Remember me on this device", "unlock": "Open",
           "opening": "Opening…", "wrong": "Wrong password.", "noscript": "Enable JavaScript to open this page."},
    "es": {"placeholder": "Contraseña", "remember": "Recordarme en este dispositivo", "unlock": "Abrir",
           "opening": "Abriendo…", "wrong": "Contraseña incorrecta.", "noscript": "Activá JavaScript para abrir esta página."},
}

COUNTRY_NAMES = {
    "en": {"AR": "Argentina", "ES": "Spain", "MX": "Mexico", "US": "the US", "CL": "Chile",
           "UY": "Uruguay", "CO": "Colombia", "PE": "Peru", "GB": "the UK"},
    "es": {"AR": "Argentina", "ES": "España", "MX": "México", "US": "EE.UU.", "CL": "Chile",
           "UY": "Uruguay", "CO": "Colombia", "PE": "Perú", "GB": "Reino Unido"},
}
