"""Keyword lists: topics, local relevance, life-stage hints and sensationalism markers.

Everything is written in lowercase without accents (matching text.normalize).
"""

TOPIC_KEYWORDS: dict[str, list[str]] = {
    "world": [
        "war", "guerra", "ceasefire", "alto el fuego", "summit", "cumbre", "onu", "united nations", "naciones unidas", "nato", "otan",
        "diplomat", "diplomacia", "sanctions", "sanciones", "invasion", "refugees", "refugiados",
        "foreign minister", "canciller", "ukraine", "ucrania", "russia", "rusia", "china", "gaza",
        "israel", "iran", "europe", "europa", "treaty", "tratado", "border", "frontera", "embassy", "embajada",
    ],
    "politics": [
        "election", "elections", "elecciones", "eleccion", "president", "presidente", "presidenta",
        "congress", "congreso", "senate", "senado", "parliament", "parlamento", "minister", "ministro",
        "ministra", "government", "gobierno", "opposition", "oposicion", "vote", "votacion", "law", "ley",
        "court", "corte", "supreme court", "tribunal", "legislators", "diputados", "senadores", "campaign",
        "campana", "decree", "decreto", "prime minister", "primer ministro", "cabinet", "gabinete",
    ],
    "economy": [
        "inflation", "inflacion", "gdp", "pbi", "pib", "recession", "recesion", "interest rate", "tasa",
        "tasas", "central bank", "banco central", "imf", "fmi", "dollar", "dolar", "peso", "exports",
        "exportaciones", "imports", "importaciones", "tariff", "tariffs", "aranceles", "arancel", "debt",
        "deuda", "unemployment", "desempleo", "desocupacion", "salaries", "salarios", "wages", "budget",
        "presupuesto", "taxes", "impuestos", "economy", "economia", "markets", "mercados", "reserves",
        "reservas", "jobs", "empleo", "pensions", "jubilaciones", "prices", "precios", "bonds", "bonos",
    ],
    "business": [
        "company", "empresa", "empresas", "merger", "fusion", "acquisition", "adquisicion", "shares",
        "acciones", "stock", "bolsa", "earnings", "ganancias", "ceo", "startup", "investment", "inversion",
        "bank", "banco", "oil", "petroleo", "industry", "industria", "retail",
    ],
    "science": [
        "scientists", "cientificos", "study", "estudio", "research", "investigacion", "nasa", "space",
        "espacio", "telescope", "telescopio", "species", "especie", "fossil", "fosil", "physics", "fisica",
        "biology", "biologia", "astronomers", "astronomos", "discovery", "descubrimiento", "mars", "marte",
        "moon", "luna", "genome", "genoma", "nobel",
    ],
    "technology": [
        "artificial intelligence", "inteligencia artificial", "ai", "ia", "chip", "chips", "semiconductor",
        "semiconductores", "software", "app", "apple", "google", "microsoft", "openai", "anthropic",
        "nvidia", "cyberattack", "ciberataque", "hackers", "smartphone", "internet",
        "robot", "robots", "tesla", "satellite", "satelite", "technology", "tecnologia", "quantum", "cuantica",
    ],
    "health": [
        "health", "salud", "hospital", "hospitales", "vaccine", "vacuna", "vacunas", "virus", "outbreak",
        "brote", "disease", "enfermedad", "cancer", "world health organization", "oms", "patients", "pacientes", "doctors",
        "medicos", "epidemic", "epidemia", "pandemic", "pandemia", "dengue", "drug", "medicamento",
        "medicamentos", "mental health", "salud mental", "obesity", "obesidad",
    ],
    "environment": [
        "climate", "clima", "climate change", "cambio climatico", "emissions", "emisiones", "wildfire",
        "incendio", "incendios", "drought", "sequia", "flood", "floods", "inundacion", "inundaciones",
        "hurricane", "huracan", "earthquake", "terremoto", "sismo", "deforestation", "deforestacion",
        "renewable", "renovables", "pollution", "contaminacion", "heatwave", "ola de calor",
    ],
    "education": [
        "school", "schools", "escuela", "escuelas", "university", "universidad", "universidades",
        "students", "estudiantes", "teachers", "docentes", "education", "educacion", "exam", "examen",
    ],
    "culture": [
        "film", "pelicula", "cine", "music", "musica", "museum", "museo", "book", "libro", "literature",
        "literatura", "festival", "art", "arte", "exhibition", "exposicion", "oscar", "grammy",
    ],
    "sports": [
        "football", "futbol", "soccer", "world cup", "mundial", "copa", "tennis", "tenis", "olympics",
        "olimpicos", "nba", "f1", "formula 1", "match", "goal", "gol", "messi", "seleccion",
        "champions", "libertadores", "rugby", "torneo", "tournament",
    ],
    "security": [
        "police", "policia", "crime", "crimen", "delito", "robbery", "robo", "murder", "asesinato",
        "homicidio", "drug trafficking", "narcotrafico", "arrested", "detenido", "detenidos", "attack",
        "ataque", "shooting", "tiroteo", "terrorism", "terrorismo",
    ],
    "entertainment": [
        "famosos", "celebrity", "celebrities", "actriz", "actor", "reality", "gran hermano", "telenovela",
        "farandula", "influencer", "influencers", "tiktoker", "streamer", "premios martin fierro",
    ],
    "lifestyle": [
        "viajes", "travel", "turismo", "tourism", "gastronomia", "restaurante", "restaurant", "moda", "fashion",
        "belleza", "beauty", "decoracion", "mascotas", "pets", "bienestar", "wellness", "dieta",
    ],
    "agro": [
        "campo", "agro", "cosecha", "harvest", "soja", "soybean", "soybeans", "trigo", "wheat", "maiz", "corn",
        "ganaderia", "livestock", "retenciones", "sociedad rural", "inta", "senasa", "granos", "grain", "agricultores",
        "farmers",
    ],
    "latam": [
        "latin america", "america latina", "latinoamerica", "argentina", "brazil", "brasil", "chile",
        "uruguay", "paraguay", "bolivia", "peru", "colombia", "venezuela", "ecuador", "mexico", "mercosur",
        "cuba", "lula", "milei",
    ],
}

# Words that suggest a local story for each country (normalized).
COUNTRY_KEYWORDS: dict[str, list[str]] = {
    "AR": ["argentina", "argentino", "argentinos", "argentinas", "buenos aires", "caba", "conurbano",
           "casa rosada", "milei", "bcra", "indec", "anses", "afip", "arca", "cordoba", "rosario",
           "mendoza", "santa fe", "tucuman", "patagonia", "malvinas", "falklands"],
    "ES": ["espana", "spain", "spanish", "espanol", "espanoles", "madrid", "barcelona", "cataluna",
           "moncloa", "congreso de los diputados", "andalucia", "valencia", "pais vasco"],
    "MX": ["mexico", "mexican", "mexicano", "mexicanos", "cdmx", "sheinbaum", "morena", "jalisco",
           "monterrey", "guadalajara", "banxico"],
    "US": ["united states", "american", "americans", "estados unidos", "eeuu", "washington",
           "white house", "casa blanca", "congress", "federal reserve", "fed"],
    "CL": ["chile", "chileno", "chilenos", "santiago de chile", "la moneda", "valparaiso"],
    "UY": ["uruguay", "uruguayo", "uruguayos", "montevideo"],
    "CO": ["colombia", "colombiano", "colombianos", "bogota", "medellin", "cali"],
    "PE": ["peru", "peruano", "peruanos", "lima"],
    "GB": ["uk", "britain", "british", "england", "scotland", "wales", "london", "downing street",
           "reino unido", "londres"],
}

# Gentle hints about what tends to matter at each life stage. They only add a
# small boost and can be switched off with profile.use_age_hints: false.
AGE_HINTS: list[tuple[int, int, list[str]]] = [
    (0, 25, ["university", "universidad", "students", "estudiantes", "scholarship", "beca",
             "first job", "primer empleo", "rent", "alquiler", "alquileres"]),
    (25, 45, ["mortgage", "hipoteca", "credito hipotecario", "rent", "alquiler", "alquileres",
              "salaries", "salarios", "wages", "jobs", "empleo", "childcare", "schools", "escuelas"]),
    (45, 65, ["pensions", "jubilaciones", "retirement", "jubilacion", "salaries", "salarios",
              "taxes", "impuestos", "health", "salud", "savings", "ahorro"]),
    (65, 200, ["pensions", "jubilaciones", "jubilados", "retirement", "pami", "health", "salud",
               "medicamentos", "medicines", "hospital"]),
]

# Opinion / commentary is excluded: we want reporting, not takes.
OPINION_URL_PARTS = ["/opinion", "/opinión", "/editorial", "/columnistas", "/columnas/", "/blogs/",
                     "/tribuna/", "/cartas-", "/analisis-opinion", "/comment/", "/commentisfree/"]
OPINION_TITLE_PREFIXES = ["opinion", "opinion:", "editorial", "column", "columna", "tribuna",
                          "carta de lectores", "commentary", "op-ed"]

# Markers of hype / loaded language. Each hit lowers a story's score and makes
# that outlet's headline less likely to be the one shown.
SENSATIONAL = [
    "shocking", "shock", "slams", "blasts", "destroys", "obliterates", "rips", "outrage", "furious",
    "you won't believe", "jaw-dropping", "bombshell", "viral", "goes viral", "meltdown", "epic",
    "insane", "chaos", "explosive", "brutal", "humiliates", "fury", "stunning", "must see",
    "impactante", "escandalo", "escandaloso", "polemica", "polemico", "furor", "explota", "estalla",
    "insolito", "increible", "tremendo", "tremenda", "fuerte cruce", "durisimo", "durisima",
    "lapidario", "lapidaria", "humillo", "humillante", "liquido", "destrozo", "fulmino", "arraso",
    "se viralizo", "viralizo", "mira", "video:", "el video", "la foto", "las fotos", "atencion",
    "ultimo momento", "urgente", "bomba", "picante", "escandalosa",
]

UI = {
    "en": {
        "top": "Most important now",
        "local": "Your country",
        "updated": "Updated",
        "articles": "{n} articles read",
        "refresh": "Refresh",
        "settings": "Settings",
        "themes_title": "What do you want to follow?",
        "themes_hint": "Type the themes you care about, in your own words (e.g. Argentine economy, artificial intelligence, Formula 1). Each one becomes a tab you can swipe to. Their order also decides what comes first in “Most important now”.",
        "theme_placeholder": "Add a theme…",
        "suggestions": "Or pick from the list",
        "pick_one": "Choose a theme…",
        "popular": "Popular",
        "all_topics": "All themes (A–Z)",
        "no_themes": "No themes yet. Type one above or pick one from the list.",
        "empty_theme": "No stories on this theme right now. Try other words, or wait for the next update.",
        "theme_count": "{n} stories now",
        "theme_count_one": "1 story now",
        "pick_themes": "Choose the themes you want to follow and the app will build a tab for each one.",
        "pick_themes_btn": "Choose my themes",
        "topics_title": "Your topics",
        "topics_hint": "Pick the tabs you want and their order. The order also sets what comes first in “Most important now”.",
        "add_topic_title": "Add your own topic",
        "topic_name": "Name (e.g. Energy)",
        "topic_keywords": "Keywords, separated by commas (e.g. oil, gas, lithium, petróleo)",
        "add": "Add",
        "remove": "Remove",
        "move_up": "Move up",
        "move_down": "Move down",
        "show_local": "Show the “Your country” tab",
        "save": "Save",
        "cancel": "Cancel",
        "reset": "Reset to defaults",
        "empty_tab": "No stories on this topic right now.",
        "read_full": "Read the full story",
        "covered_by": "Covered by",
        "settings_note": "Your themes are saved on this device.",
        "push_title": "Your daily news is ready",
        "bell_on": "Daily reminder on",
        "bell_off": "Turn on daily reminder",
        "push_unsupported": "This browser can't receive notifications.",
        "push_ios": "On iPhone, add this site to your Home Screen first (Share → Add to Home Screen), then open it from there and tap the bell again.",
        "push_denied": "Notifications are blocked. Allow them for this app in your phone's settings, then try again.",
        "push_failed": "Couldn't turn on notifications: {err}",
        "push_step1": "Last step: copy this code and save it in GitHub as the secret PUSH_SUBSCRIPTIONS. If you already have codes from other devices, put each on its own line.",
        "push_copy": "Copy code",
        "push_copied": "Copied ✓",
        "push_open_github": "Open GitHub secrets",
        "push_done": "Done",
        "push_off_hint": "You'll get a reminder every morning with the top headlines.",
        "sources_one": "1 outlet",
        "sources_many": "{n} outlets",
        "single_source": "single source",
        "why": "Why you see this",
        "covered": "covered by {n} independent outlets",
        "matches": "matches",
        "local_match": "relevant to {country}",
        "read_at": "Read at",
        "empty": "No stories right now. Check back after the next update.",
        "greeting": "Good morning! Your news for {date}",
        "more": "More on the site",
        "about": "Stories are ranked by how many independent outlets report them, how recent they are and how well they match your profile. Opinion pieces are excluded and hyped headlines are down-ranked.",
        "topics": {
            "world": "World", "politics": "Politics", "economy": "Economy", "business": "Business",
            "science": "Science", "technology": "Technology", "health": "Health",
            "environment": "Environment", "education": "Education", "culture": "Culture",
            "sports": "Sports", "security": "Security", "latam": "Latin America",
            "entertainment": "Entertainment", "lifestyle": "Lifestyle", "agro": "Farming",
        },
    },
    "es": {
        "top": "Lo más importante",
        "local": "Tu país",
        "updated": "Actualizado",
        "articles": "{n} artículos leídos",
        "refresh": "Actualizar",
        "settings": "Ajustes",
        "themes_title": "¿Qué temas querés seguir?",
        "themes_hint": "Escribí los temas que te interesan, con tus palabras (ej. economía argentina, inteligencia artificial, Fórmula 1). Cada uno se convierte en una pestaña. El orden también define qué aparece primero en “Lo más importante”.",
        "theme_placeholder": "Agregar un tema…",
        "suggestions": "O elegí de la lista",
        "pick_one": "Elegí un tema…",
        "popular": "Populares",
        "all_topics": "Todos los temas (A–Z)",
        "no_themes": "Todavía no elegiste temas. Escribí uno arriba o elegí uno de la lista.",
        "empty_theme": "Por ahora no hay noticias de este tema. Probá con otras palabras o esperá a la próxima actualización.",
        "theme_count": "{n} noticias ahora",
        "theme_count_one": "1 noticia ahora",
        "pick_themes": "Elegí los temas que querés seguir y la app arma una pestaña para cada uno.",
        "pick_themes_btn": "Elegir mis temas",
        "topics_title": "Tus temas",
        "topics_hint": "Elegí las pestañas que querés y su orden. El orden también define qué aparece primero en “Lo más importante”.",
        "add_topic_title": "Agregar un tema propio",
        "topic_name": "Nombre (ej. Energía)",
        "topic_keywords": "Palabras clave separadas por comas (ej. petróleo, gas, litio, Vaca Muerta)",
        "add": "Agregar",
        "remove": "Quitar",
        "move_up": "Subir",
        "move_down": "Bajar",
        "show_local": "Mostrar la pestaña “Tu país”",
        "save": "Guardar",
        "cancel": "Cancelar",
        "reset": "Volver a los valores iniciales",
        "empty_tab": "No hay noticias de este tema por ahora.",
        "read_full": "Leer la nota completa",
        "covered_by": "Cubierto por",
        "settings_note": "Tus temas se guardan en este dispositivo.",
        "push_title": "Tus noticias de hoy están listas",
        "bell_on": "Recordatorio diario activado",
        "bell_off": "Activar recordatorio diario",
        "push_unsupported": "Este navegador no puede recibir notificaciones.",
        "push_ios": "En iPhone, primero agregá este sitio a tu pantalla de inicio (Compartir → Agregar a inicio), abrilo desde ahí y tocá la campanita de nuevo.",
        "push_denied": "Las notificaciones están bloqueadas. Permitilas para esta app en los ajustes del teléfono y volvé a intentar.",
        "push_failed": "No se pudieron activar las notificaciones: {err}",
        "push_step1": "Último paso: copiá este código y guardalo en GitHub como el secreto PUSH_SUBSCRIPTIONS. Si ya tenés códigos de otros dispositivos, poné cada uno en su propia línea.",
        "push_copy": "Copiar código",
        "push_copied": "Copiado ✓",
        "push_open_github": "Abrir secretos de GitHub",
        "push_done": "Listo",
        "push_off_hint": "Vas a recibir un recordatorio cada mañana con los titulares principales.",
        "sources_one": "1 medio",
        "sources_many": "{n} medios",
        "single_source": "fuente única",
        "why": "Por qué lo ves",
        "covered": "cubierto por {n} medios independientes",
        "matches": "coincide con",
        "local_match": "relevante para {country}",
        "read_at": "Leer en",
        "empty": "No hay noticias por ahora. Volvé a mirar después de la próxima actualización.",
        "greeting": "¡Buen día! Tus noticias del {date}",
        "more": "Más en el sitio",
        "about": "Las noticias se ordenan según cuántos medios independientes las cubren, qué tan recientes son y cuánto coinciden con tu perfil. Se excluyen columnas de opinión y se penalizan los titulares sensacionalistas.",
        "topics": {
            "world": "Mundo", "politics": "Política", "economy": "Economía", "business": "Negocios",
            "science": "Ciencia", "technology": "Tecnología", "health": "Salud",
            "environment": "Ambiente", "education": "Educación", "culture": "Cultura",
            "sports": "Deportes", "security": "Seguridad", "latam": "América Latina",
            "entertainment": "Espectáculos", "lifestyle": "Estilo de vida", "agro": "Campo",
        },
    },
}

LOCK_UI = {
    "en": {"placeholder": "Password", "remember": "Remember me on this device", "unlock": "Open",
           "opening": "Opening…", "wrong": "Wrong password.", "noscript": "Enable JavaScript to open this page."},
    "es": {"placeholder": "Contraseña", "remember": "Recordarme en este dispositivo", "unlock": "Abrir",
           "opening": "Abriendo…", "wrong": "Contraseña incorrecta.", "noscript": "Activá JavaScript para abrir esta página."},
}

COUNTRY_NAMES = {
    "en": {"AR": "Argentina", "ES": "Spain", "MX": "Mexico", "US": "the US", "CL": "Chile",
           "UY": "Uruguay", "CO": "Colombia", "PE": "Peru", "GB": "the UK"},
    "es": {"AR": "Argentina", "ES": "España", "MX": "México", "US": "EE.UU.", "CL": "Chile",
           "UY": "Uruguay", "CO": "Colombia", "PE": "Perú", "GB": "Reino Unido"},
}


# ---------------------------------------------------------------------------
# Themes typed in the app are matched against this dictionary.
#   names    - what people may type (es/en, normalized); the first one is not special
#   label    - how the suggestion chip is shown
#   topic    - built-in topic whose scores (incl. URL sections) also count
#   keywords - words that mark a story as being about the theme
# Anything not found here is matched by the words the user typed.
# ---------------------------------------------------------------------------
TOPIC_ALIASES = {
    "world": "mundo world internacional international noticias-del-mundo",
    "politics": "politica politics gobierno government",
    "economy": "economia economy finanzas finance",
    "business": "negocios business empresas companies",
    "science": "ciencia science",
    "technology": "tecnologia technology tech",
    "health": "salud health medicina medicine",
    "environment": "ambiente medio-ambiente environment ecologia naturaleza nature",
    "education": "educacion education escuelas universidades",
    "culture": "cultura culture arte art",
    "sports": "deportes sports sport",
    "security": "seguridad security policiales crimen crime justicia",
    "latam": "america-latina latinoamerica latin-america latam sudamerica",
    "entertainment": "espectaculos entretenimiento entertainment famosos celebrities farandula television",
    "lifestyle": "estilo-de-vida lifestyle viajes travel turismo gastronomia moda fashion",
    "agro": "campo agro agricultura agriculture farming ganaderia",
}

CONCEPTS = [
    {"id": "ai", "label": {"es": "Inteligencia artificial", "en": "Artificial intelligence"}, "topic": "technology",
     "names": ["ia", "ai", "inteligencia artificial", "artificial intelligence"],
     "keywords": ["inteligencia artificial", "artificial intelligence", "ia", "ai", "openai", "chatgpt", "anthropic",
                  "claude", "gemini", "nvidia", "machine learning", "aprendizaje automatico", "llm", "deepmind",
                  "copilot", "ia generativa", "generative ai", "chatbot", "chatbots"]},
    {"id": "f1", "label": {"es": "Fórmula 1", "en": "Formula 1"}, "topic": None,
     "names": ["formula 1", "f1", "formula uno", "automovilismo", "motorsport"],
     "keywords": ["formula 1", "f1", "gran premio", "grand prix", "colapinto", "verstappen", "hamilton", "leclerc",
                  "alpine", "ferrari", "red bull racing", "mclaren", "norris", "piastri", "fia"]},
    {"id": "football", "label": {"es": "Fútbol", "en": "Football"}, "topic": "sports",
     "names": ["futbol", "football", "soccer"],
     "keywords": ["futbol", "football", "soccer", "seleccion argentina", "messi", "river plate", "boca juniors",
                  "liga profesional", "copa libertadores", "libertadores", "champions league", "mundial 2026",
                  "world cup", "premier league", "afa", "fifa", "conmebol", "scaloni"]},
    {"id": "tennis", "label": {"es": "Tenis", "en": "Tennis"}, "topic": "sports",
     "names": ["tenis", "tennis"],
     "keywords": ["tenis", "tennis", "atp", "wta", "grand slam", "wimbledon", "roland garros", "us open",
                  "australian open", "copa davis", "davis cup"]},
    {"id": "crypto", "label": {"es": "Criptomonedas", "en": "Crypto"}, "topic": None,
     "names": ["cripto", "criptomonedas", "crypto", "cryptocurrency", "cryptocurrencies", "bitcoin", "blockchain"],
     "keywords": ["bitcoin", "btc", "ethereum", "cripto", "criptomonedas", "criptomoneda", "crypto",
                  "cryptocurrency", "blockchain", "stablecoin", "stablecoins", "binance"]},
    {"id": "geopolitics", "label": {"es": "Geopolítica", "en": "Geopolitics"}, "topic": "world",
     "names": ["geopolitica", "geopolitics", "relaciones internacionales", "international relations", "diplomacia",
               "diplomacy"],
     "keywords": ["geopolitica", "geopolitics", "diplomacia", "diplomacy", "cumbre", "summit", "otan", "nato",
                  "sanciones", "sanctions", "aranceles", "tariffs", "onu", "united nations", "g20", "g7", "brics"]},
    {"id": "middle_east", "label": {"es": "Medio Oriente", "en": "Middle East"}, "topic": None,
     "names": ["medio oriente", "oriente medio", "middle east", "israel", "gaza", "iran"],
     "keywords": ["gaza", "israel", "israeli", "hamas", "hezbollah", "iran", "libano", "lebanon", "siria", "syria",
                  "cisjordania", "west bank", "yemen", "huties", "houthis", "arabia saudita", "saudi arabia",
                  "palestinos", "palestinians", "netanyahu", "teheran", "tehran"]},
    {"id": "ukraine", "label": {"es": "Guerra en Ucrania", "en": "War in Ukraine"}, "topic": None,
     "names": ["ucrania", "ukraine", "guerra en ucrania", "war in ukraine", "rusia", "russia"],
     "keywords": ["ucrania", "ukraine", "ukrainian", "rusia", "russia", "russian", "putin", "zelensky", "kiev",
                  "kyiv", "moscu", "moscow", "kremlin", "donbas"]},
    {"id": "china", "label": {"es": "China", "en": "China"}, "topic": None,
     "names": ["china", "asia"],
     "keywords": ["china", "chino", "china's", "chinese", "pekin", "beijing", "xi jinping", "taiwan", "hong kong"]},
    {"id": "usa", "label": {"es": "Estados Unidos", "en": "United States"}, "topic": None,
     "names": ["estados unidos", "eeuu", "ee.uu", "usa", "united states", "us politics"],
     "keywords": ["estados unidos", "eeuu", "united states", "washington", "casa blanca", "white house", "trump",
                  "reserva federal", "federal reserve", "wall street", "pentagono", "pentagon"]},
    {"id": "europe", "label": {"es": "Europa", "en": "Europe"}, "topic": None,
     "names": ["europa", "europe", "union europea", "european union"],
     "keywords": ["union europea", "european union", "bruselas", "brussels", "comision europea",
                  "european commission", "eurozona", "eurozone", "bce", "ecb", "europa", "europe", "macron",
                  "alemania", "germany", "francia", "france", "reino unido", "britain"]},
    {"id": "elections", "label": {"es": "Elecciones", "en": "Elections"}, "topic": "politics",
     "names": ["elecciones", "elections", "electoral", "votaciones"],
     "keywords": ["elecciones", "eleccion", "elections", "election", "votacion", "voters", "votantes", "candidato",
                  "candidata", "candidate", "encuesta", "encuestas", "polls", "campana electoral", "balotaje",
                  "runoff", "comicios"]},
    {"id": "inflation", "label": {"es": "Inflación y precios", "en": "Inflation and prices"}, "topic": "economy",
     "names": ["inflacion", "inflation", "precios", "prices", "costo de vida", "cost of living"],
     "keywords": ["inflacion", "inflation", "ipc", "cpi", "precios", "prices", "indec", "canasta basica",
                  "tarifas", "costo de vida", "cost of living"]},
    {"id": "dollar", "label": {"es": "Dólar y reservas", "en": "Dollar and reserves"}, "topic": "economy",
     "names": ["dolar", "dollar", "tipo de cambio", "exchange rate", "reservas", "bcra", "banco central"],
     "keywords": ["dolar", "dollar", "tipo de cambio", "exchange rate", "cepo", "bcra", "banco central",
                  "reservas", "devaluacion", "devaluation", "fmi", "imf"]},
    {"id": "markets", "label": {"es": "Mercados", "en": "Markets"}, "topic": "economy",
     "names": ["mercados", "bolsa", "markets", "stock market", "acciones", "stocks", "inversiones", "investing",
               "finanzas personales"],
     "keywords": ["bolsa", "mercados", "markets", "wall street", "merval", "nasdaq", "dow jones", "acciones",
                  "stocks", "bonos", "bonds", "riesgo pais", "inversores", "investors", "s&p 500"]},
    {"id": "energy", "label": {"es": "Energía", "en": "Energy"}, "topic": None,
     "names": ["energia", "energy", "petroleo", "oil", "gas", "vaca muerta"],
     "keywords": ["energia", "energy", "petroleo", "oil", "gas", "vaca muerta", "ypf", "opep", "opec",
                  "renovables", "renewable", "renewables", "solar", "eolica", "nuclear", "electricidad",
                  "electricity", "litio", "lithium", "gnl", "lng"]},
    {"id": "mining", "label": {"es": "Minería", "en": "Mining"}, "topic": None,
     "names": ["mineria", "mining", "litio", "lithium"],
     "keywords": ["mineria", "minera", "mining", "litio", "lithium", "cobre", "copper", "rigi"]},
    {"id": "space", "label": {"es": "Espacio", "en": "Space"}, "topic": "science",
     "names": ["espacio", "space", "astronomia", "astronomy", "nasa"],
     "keywords": ["nasa", "spacex", "espacio", "space", "cohete", "rocket", "satelite", "satellite", "astronomos",
                  "astronomers", "telescopio", "telescope", "luna", "moon", "marte", "mars", "conae", "artemis"]},
    {"id": "cyber", "label": {"es": "Ciberseguridad", "en": "Cybersecurity"}, "topic": "technology",
     "names": ["ciberseguridad", "cybersecurity", "hackers", "seguridad informatica"],
     "keywords": ["ciberseguridad", "cybersecurity", "ciberataque", "cyberattack", "hackers", "hackeo",
                  "ransomware", "filtracion de datos", "data breach", "malware", "phishing"]},
    {"id": "climate", "label": {"es": "Cambio climático", "en": "Climate change"}, "topic": "environment",
     "names": ["cambio climatico", "climate change", "clima", "climate", "calentamiento global"],
     "keywords": ["cambio climatico", "climate change", "calentamiento global", "global warming", "emisiones",
                  "emissions", "cop30", "cop31", "sequia", "drought", "ola de calor", "heatwave", "incendios",
                  "wildfire", "wildfires", "inundaciones", "floods", "glaciares", "glaciers"]},
    {"id": "housing", "label": {"es": "Vivienda", "en": "Housing"}, "topic": None,
     "names": ["vivienda", "housing", "alquileres", "alquiler", "rent", "inmobiliario", "real estate"],
     "keywords": ["vivienda", "viviendas", "housing", "alquiler", "alquileres", "rent", "hipoteca",
                  "hipotecarios", "mortgage", "mortgages", "creditos hipotecarios", "inmobiliario", "real estate"]},
    {"id": "pensions", "label": {"es": "Jubilaciones", "en": "Pensions"}, "topic": None,
     "names": ["jubilaciones", "jubilados", "pensiones", "pensions", "retirement"],
     "keywords": ["jubilaciones", "jubilados", "jubilacion", "pensiones", "pensions", "anses", "pami",
                  "retirement", "haber minimo"]},
    {"id": "jobs", "label": {"es": "Empleo y salarios", "en": "Jobs and wages"}, "topic": None,
     "names": ["empleo", "trabajo", "jobs", "employment", "salarios", "wages", "sindicatos", "unions"],
     "keywords": ["empleo", "desempleo", "jobs", "employment", "unemployment", "salarios", "salario", "wages",
                  "paritarias", "sindicatos", "unions", "cgt", "huelga", "strike", "despidos", "layoffs",
                  "reforma laboral"]},
    {"id": "migration", "label": {"es": "Migración", "en": "Migration"}, "topic": None,
     "names": ["migracion", "inmigracion", "migration", "immigration", "migrantes", "refugiados"],
     "keywords": ["migracion", "migrantes", "inmigracion", "inmigrantes", "migration", "migrants",
                  "immigration", "refugiados", "refugees", "deportaciones", "deportations", "asilo", "asylum"]},
    {"id": "movies", "label": {"es": "Cine y series", "en": "Film and TV"}, "topic": "culture",
     "names": ["cine", "peliculas", "movies", "film", "series", "cine y series"],
     "keywords": ["cine", "pelicula", "peliculas", "film", "movie", "movies", "oscar", "oscars", "cannes",
                  "netflix", "hollywood", "estreno", "premiere", "director de cine", "taquilla", "box office"]},
    {"id": "music", "label": {"es": "Música", "en": "Music"}, "topic": "culture",
     "names": ["musica", "music"],
     "keywords": ["musica", "music", "album", "concierto", "concert", "grammy", "grammys", "cantante", "singer",
                  "rock", "recital", "lollapalooza"]},
    {"id": "books", "label": {"es": "Libros", "en": "Books"}, "topic": "culture",
     "names": ["libros", "books", "literatura", "literature"],
     "keywords": ["libro", "libros", "book", "books", "novela", "novel", "literatura", "literature", "escritor",
                  "escritora", "writer", "feria del libro", "premio nobel de literatura"]},
    {"id": "gaming", "label": {"es": "Videojuegos", "en": "Video games"}, "topic": None,
     "names": ["videojuegos", "gaming", "video games", "videogames", "gamers"],
     "keywords": ["videojuego", "videojuegos", "video game", "video games", "gaming", "playstation", "xbox",
                  "nintendo", "steam", "esports"]},
    {"id": "cars", "label": {"es": "Autos", "en": "Cars"}, "topic": None,
     "names": ["autos", "cars", "automoviles", "motor"],
     "keywords": ["autos", "automotriz", "automotive", "cars", "vehiculos", "vehicles", "vehiculos electricos",
                  "electric vehicles", "tesla", "patentamientos", "toyota", "volkswagen"]},
    {"id": "startups", "label": {"es": "Emprendedores y startups", "en": "Startups"}, "topic": "business",
     "names": ["startups", "startup", "emprendimientos", "emprendedores", "entrepreneurs"],
     "keywords": ["startup", "startups", "emprendedores", "emprendimiento", "unicornio", "unicorn",
                  "venture capital", "capital de riesgo", "fintech", "mercado libre", "mercadolibre"]},
    {"id": "mental_health", "label": {"es": "Salud mental", "en": "Mental health"}, "topic": None,
     "names": ["salud mental", "mental health"],
     "keywords": ["salud mental", "mental health", "ansiedad", "anxiety", "depresion", "depression", "suicidio",
                  "suicide", "psicologia", "psychology", "estres", "stress"]},
]

# Chips offered when choosing themes in the app (built-in topic names or concept ids).
SUGGESTED_THEMES = ["economy", "politics", "world", "technology", "ai", "science", "health", "sports", "football",
                    "f1", "middle_east", "ukraine", "usa", "latam", "energy", "markets", "climate", "culture",
                    "movies", "agro"]
